version: "3.8"
services:
  redis:
    image: redis:7.2.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  postgres:
    image: postgres:15.4-bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  rabbit-mq:
    image: rabbitmq:3.12.4-management
    container_name: rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
